---
version: '3.4'

services:
  uds.mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    ports:
      - "1187:1433"
    environment:
      MSSQL_SA_PASSWORD: ${MSSQLSAPASSWORD:?database password not set}
      ACCEPT_EULA: "Y"
    volumes:
      - uds_mssql_data:/var/opt/mssql/data
  uds.net.api:
    image: ${DOCKER_REGISTRY-}udsnet
    build:
      context: .
      dockerfile: UDS.Net.API/Dockerfile
    ports:
      - "4801:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=server=uds.mssql,1433;user id=sa;password=${MSSQLSAPASSWORD:?api needs database password};database=UDS_API;TrustServerCertificate=True
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: ['uds.mssql']
  uds.net.web.mvc:
    image: ${DOCKER_REGISTRY-}udsnetweb
    build:
      context: .
      dockerfile: UDS.Net.Web.MVC/Dockerfile
    ports:
      - "4811:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DownstreamApis__UDSNetApi__BaseUrl=http://uds.net.api:80/api
      - ConnectionStrings__AuthServiceConnection=server=uds.mssql,1433;user id=sa;password=${MSSQLSAPASSWORD:?app needs database password};database=UDS_APP;TrustServerCertificate=True
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: ['uds.net.api', 'uds.mssql']
volumes:
  uds_mssql_data: